import movie1 from './images/got.jpg';
import movie2 from './images/a.jpeg';
import movie3 from './images/ae.jpeg';
import movie4 from './images/bd.jpg';
import movie5 from './images/f.jpeg';
import movie6 from './images/fg.jpg';
import movie7 from './images/t.jpeg';
import movie8 from './images/tdk.jpg';
import movie9 from './images/tg.jpg';
import movie10 from './images/ts.jpg';
import movie11 from './images/fg.jpeg';
import movie12 from './images/ram.jpg';
import movie13 from './images/tg2.jpg';
import movie14 from './images/tg3.jpeg';
import movie15 from './images/aiw.jpeg';
import movie16 from './images/j.jpg';
import movie17 from './images/t.jpg';
import movie18 from './images/bnn.jpg';
import movie19 from './images/to.jpeg';
import movie20 from './images/vs.jpg';
import movie21 from './images/sm.jpg';
import i18n from 'i18next';
import { useTranslation } from 'react-i18next';

const useMovieData = () => {
    const { t } = useTranslation();

    const movies = [
        {
            id: 1,
            title: t('gameOfThrones'),
            description: t('gameOfThronesDescription'),
            duration: t('eightSeasons'),
            rating: 'TV-MA',
            reviews: '9.3/10',
            cast: ['Emilia Clarke', 'Peter Dinklage', 'Kit Harington'],
            genre: [t('action'), t('adventure'), t('drama')],
            ratio: '9:2',
            watched: '40 million',
            rewatched: '2 million',
            image: movie1,
        },
        {
            id: 2,
            title: t('avatar'),
            description: t('avatarDescription'),
            duration: t('oneSixtyTwoMin'),
            rating: 'PG-13',
            reviews: '7.8/10',
            cast: ['Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver'],
            genre: [t('action'), t('adventure'), t('fantasy')],
            ratio: '7:3',
            watched: '800 million',
            rewatched: '100 million',
            image: movie2,
        },
        {
            id: 3,
            title: t('avengersEndgame'),
            description: t('avengersEndgameDescription'),
            duration: t('oneEightyOneMin'),
            rating: 'PG-13',
            reviews: '8.4/10',
            cast: ['Robert Downey Jr.', 'Chris Evans', 'Mark Ruffalo'],
            genre: [t('action'), t('adventure'), t('drama')],
            ratio: '10:1',
            watched: '500 million',
            rewatched: '100 million',
            image: movie3,
        },
        {
            id: 4,
            title: t('breakingBad'),
            description: t('breakingBadDescription'),
            duration: t('breakingBadDuration'),
            rating: 'TV-MA',
            reviews: '9.5/10',
            cast: ['Bryan Cranston', 'Aaron Paul', 'Anna Gunn'],
            genre: [t('crime'), t('drama'), t('thriller')],
            ratio: '9:2',
            watched: '45 million',
            rewatched: '12 million',
            image: movie4,
        },
        {
            id: 5,
            title: t('friends'),
            description: t('friendsDescription'),
            duration: t('friendsDuration'),
            rating: 'TV-14',
            reviews: '8.5/10',
            cast: ['Jennifer Aniston', 'Courteney Cox', 'Lisa Kudrow'],
            genre: [t('comedy'), t('romance')],
            ratio: '9:2',
            watched: '30 million',
            rewatched: '2 million',
            image: movie5,
        },
        {
            id: 6,
            title: t('forrestGump'),
            description: t('forrestGumpDescription'),
            duration: t('forestGumpDuration'),
            rating: 'PG-13',
            reviews: '8.8/10',
            cast: ['Tom Hanks', 'Robin Wright', 'Gary Sinise'],
            genre: [t('drama'), t('romance')],
            ratio: '8:3',
            watched: '55 million',
            rewatched: '5 million',
            image: movie6,
        },
        {
            id: 7,
            title: t('titanic'),
            description: t('titanicDescription'),
            duration: t('titanicDuration'),
            rating: 'PG-13',
            reviews: '7.8/10',
            cast: ['Leonardo DiCaprio', 'Kate Winslet', 'Billy Zane'],
            genre: [t('drama'), t('romance')],
            ratio: '11:0',
            watched: '150 million',
            rewatched: '40 million',
            image: movie7,
        },
        {
            id: 8,
            title: t('darkKnight'),
            description: t('darkKnightDescription'),
            duration: t('darkKnightDuration'),
            rating: 'PG-13',
            reviews: '9.0/10',
            cast: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart'],
            genre: [t('action'), t('crime'), t('drama')],
            ratio: '9:2',
            watched: '60 million',
            rewatched: '12 million',
            image: movie8,
        },
        {
            id: 9,
            title: t('godfather'),
            description: t('godfatherDescription'),
            duration: t('godfatherDuration'),
            rating: 'R',
            reviews: '9.2/10',
            cast: ['Marlon Brando', 'Al Pacino', 'James Caan'],
            genre: [t('crime'), t('drama')],
            ratio: '10:1',
            watched: '60 million',
            rewatched: '5.8 million',
            image: movie9,
        },
        {
            id: 10,
            title: t('simpsons'),
            description: t('simpsonsDescription'),
            duration: t('simpsonsDuration'),
            rating: 'TV-PG',
            reviews: '8.6/10',
            cast: ['Dan Castellaneta', 'Nancy Cartwright', 'Harry Shearer'],
            genre: [t('animation'), t('comedy')],
            ratio: '8:2',
            watched: '35 million',
            rewatched: '10 million',
            image: movie10,
        },
        {
            id: 11,
            title: t('familyGuy'),
            description: t('familyGuyDescription'),
            duration: t('familyGuyDuration'),
            rating: 'TV-14',
            reviews: '8.1/10',
            cast: ['Seth MacFarlane', 'Alex Borstein', 'Seth Green'],
            genre: [t('animation'), t('comedy')],
            ratio: '7:3',
            watched: '20 million',
            rewatched: '1.3 million',
            image: movie11,
        },
        {
            id: 12,
            title: t('rickAndMorty'),
            description: t('rickAndMortyDescription'),
            duration: t('rickAndMortyDuration'),
            rating: 'TV-MA',
            reviews: '9.2/10',
            cast: ['Justin Roiland', 'Chris Parnell', 'Spencer Grammer'],
            genre: [t('animation'), t('adventure'), t('comedy')],
            ratio: '9:2',
            watched: '40 million',
            rewatched: '8 million',
            image: movie12,
        },
        {
            id: 13,
            title: t('godfatherPart2'),
            description: t('godfatherPart2Description'),
            duration: t('godfatherPart2Duration'),
            rating: 'R',
            reviews: '9.0/10',
            cast: ['Al Pacino', 'Robert De Niro', 'Robert Duvall'],
            genre: [t('crime'), t('drama')],
            ratio: '9:2',
            watched: '40 million',
            rewatched: '2.1 million',
            image: movie13,
        },
        {
            id: 14,
            title: t('godfatherPart3'),
            description: t('godfatherPart3Description'),
            duration: t('godfatherPart3Duration'),
            rating: 'R',
            reviews: '7.6/10',
            cast: ['Al Pacino', 'Diane Keaton', 'Andy Garcia'],
            genre: [t('crime'), t('drama')],
            ratio: '9:2',
            watched: '35 million',
            rewatched: '2.2 million',
            image: movie14,
        },
        {
            id: 15,
            title: t('infinityWar'),
            description: t('inifinityWarDescription'),
            duration: t('inifinityWarDuration'),
            rating: 'PG-13',
            reviews: '8.4/10',
            cast: ['Robert Downey Jr.', 'Chris Hemsworth', 'Mark Ruffalo'],
            genre: [t('action'), t('adventure'), t('scifi')],
            ratio: '11:0',
            watched: '500 million',
            rewatched: '200 million',
            image: movie15,
        },
        {
            id: 16,
            title: t('joker'),
            description: t('jokerDescription'),
            duration: t('jokerDuration'),
            rating: 'R',
            reviews: '8.4/10',
            cast: ['Joaquin Phoenix', 'Robert De Niro', 'Zazie Beetz'],
            genre: [t('crime'), t('drama'), t('thriller')],
            ratio: '9:2',
            watched: '30 million',
            rewatched: '2.5 million',
            image: movie16,
        },
        {
            id: 17,
            title: t('ted'),
            description: t('tedDescription'),
            duration: t('tedDuration'),
            rating: 'R',
            reviews: '6.9/10',
            cast: ['Mark Wahlberg', 'Mila Kunis', 'Seth MacFarlane'],
            genre: [t('comedy'), t('fantasy')],
            ratio: '7:3',
            watched: '18 million',
            rewatched: '1.5 million',
            image: movie17,
        },
        {
            id: 18,
            title: t('brooklynNineNine'),
            description: t('brooklynNineNineDescription'),
            duration: t('brooklynNineNineDuration'),
            rating: 'TV-14',
            reviews: '8.4/10',
            cast: ['Andy Samberg', 'Terry Crews', 'Stephanie Beatriz'],
            genre: [t('comedy'), t('crime')],
            ratio: '9:2',
            watched: '40 million',
            rewatched: '8 million',
            image: movie18,
        },
        {
            id: 19,
            title: t('theOffice'),
            description: t('theOfficeDescription'),
            duration: t('theOfficeDuration'),
            rating: 'TV-14',
            reviews: '8.9/10',
            cast: ['Steve Carell', 'Jenna Fischer', 'John Krasinski'],
            genre: [t('comedy')],
            ratio: '10:1',
            watched: '30 million',
            rewatched: '5 million',
            image: movie19,
        },
        {
            id: 20,
            title: t('vinlandSaga'),
            description: t('vinlandSagaDescription'),
            duration: t('vinlandSagaDuration'),
            rating: 'TV-MA',
            reviews: '8.8/10',
            cast: ['Shizuka Ishigami', 'Yûto Uemura', 'Kenichiro Matsuda'],
            genre: [t('animation'), t('action'), t('adventure')],
            ratio: '8:2',
            watched: '4 million',
            rewatched: '1 million',
            image: movie20,
        },
        {
            id: 21,
            title: t('spiderman'),
            description: t('spidermanDescription'),
            duration: t('spidermanDuration'),
            rating: 'PG',
            reviews: '8.4/10',
            cast: ['Shameik Moore', 'Jake Johnson', 'Hailee Steinfeld'],
            genre: [t('animation'), t('action'), t('adventure')],
            ratio: '10:1',
            watched: '300 million',
            rewatched: '100 million',
            image: movie21,
        }
    ];

    return movies;
}

export default useMovieData;