import movie1 from './images/got.jpg';
import movie2 from './images/a.jpeg';
import movie3 from './images/ae.jpeg';
import movie4 from './images/bd.jpg';
import movie5 from './images/f.jpeg';
import movie6 from './images/fg.jpg';
import movie7 from './images/t.jpeg';
import movie8 from './images/tdk.jpg';
import movie9 from './images/tg.jpg';
import movie10 from './images/ts.jpg';
import movie11 from './images/fg.jpeg';
import movie12 from './images/ram.jpg';
import movie13 from './images/tg2.jpg';
import movie14 from './images/tg3.jpeg';
import movie15 from './images/aiw.jpeg';
import movie16 from './images/j.jpg';
import movie17 from './images/t.jpg';
import movie18 from './images/bnn.jpg';
import movie19 from './images/to.jpeg';
import movie20 from './images/vs.jpg';
import movie21 from './images/sm.jpg';

const movieData = [
    {
        id: 1,
        title: 'Game of Thrones',
        description: 'Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.',
        duration: '8 Seasons',
        rating: 'TV-MA',
        reviews: '9.3/10',
        cast: ['Emilia Clarke', 'Peter Dinklage', 'Kit Harington'],
        genre: ['Action', 'Adventure', 'Drama'],
        ratio: '9:2',
        watched: '40 million',
        rewatched: '2 million',
        image: movie1,
    },
    {
        id: 2,
        title: 'Avatar',
        description: 'A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.',
        duration: '162 min',
        rating: 'PG-13',
        reviews: '7.8/10',
        cast: ['Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver'],
        genre: ['Action', 'Adventure', 'Fantasy'],
        ratio: '7:3',
        watched: '800 million',
        rewatched: '100 million',
        image: movie2,
    },
    {
        id: 3,
        title: 'Avengers: Endgame',
        description: 'After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos\' actions and restore balance to the universe.',
        duration: '181 min',
        rating: 'PG-13',
        reviews: '8.4/10',
        cast: ['Robert Downey Jr.', 'Chris Evans', 'Mark Ruffalo'],
        genre: ['Action', 'Adventure', 'Drama'],
        ratio: '10:1',
        watched: '500 million',
        rewatched: '100 million',
        image: movie3,
},
    {
        id: 4,
        title: 'Breaking Bad',
        description: 'A high school chemistry teacher turned methamphetamine manufacturing drug dealer teams up with a former student.',
        duration: '5 Seasons',
        rating: 'TV-MA',
        reviews: '9.5/10',
        cast: ['Bryan Cranston', 'Aaron Paul', 'Anna Gunn'],
        genre: ['Crime', 'Drama', 'Thriller'],
        ratio: '9:2',
        watched: '45 million',
        rewatched: '12 million',
        image: movie4,
        },
    {
        id: 5,
        title: 'Friends',
        description: 'Follows the personal and professional lives of six twenty to thirty-something-year-old friends living in Manhattan.',
        duration: '10 Seasons',
        rating: 'TV-14',
        reviews: '8.5/10',
        cast: ['Jennifer Aniston', 'Courteney Cox', 'Lisa Kudrow'],
        genre: ['Comedy', 'Romance'],
        ratio: '9:2',
        watched: '30 million',
        rewatched: '2 million',
        image: movie5,
    },
    {
        id: 6,
        title: 'Forrest Gump',
        description: 'The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.',
        duration: '142 min',
        rating: 'PG-13',
        reviews: '8.8/10',
        cast: ['Tom Hanks', 'Robin Wright', 'Gary Sinise'],
        genre: ['Drama', 'Romance'],
        ratio: '8:3',
        watched: '55 million',
        rewatched: '5 million',
        image: movie6,
    },
    {
        id: 7,
        title: 'Titanic',
        description: 'A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.',
        duration: '195 min',
        rating: 'PG-13',
        reviews: '7.8/10',
        cast: ['Leonardo DiCaprio', 'Kate Winslet', 'Billy Zane'],
        genre: ['Drama', 'Romance'],
        ratio: '11:0',
        watched: '150 million',
        rewatched: '40 million',
        image: movie7,
    },
    {
        id: 8,
        title: 'The Dark Knight',
        description: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
        duration: '152 min',
        rating: 'PG-13',
        reviews: '9.0/10',
        cast: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart'],
        genre: ['Action', 'Crime', 'Drama'],
        ratio: '9:2',
        watched: '60 million',
        rewatched: '12 million',
        image: movie8,
    },
    {
        id: 9,
        title: 'The Godfather',
        description: 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
        duration: '175 min',
        rating: 'R',
        reviews: '9.2/10',
        cast: ['Marlon Brando', 'Al Pacino', 'James Caan'],
        genre: ['Crime', 'Drama'],
        ratio: '10:1',
        watched: '60 million',
        rewatched: '5.8 million',
        image: movie9,
    },
    {
        id: 10,
        title: 'The Simpsons',
        description: 'The satiric adventures of a working-class family in the misfit city of Springfield.',
        duration: '33 Seasons',
        rating: 'TV-PG',
        reviews: '8.6/10',
        cast: ['Dan Castellaneta', 'Nancy Cartwright', 'Harry Shearer'],
        genre: ['Animation', 'Comedy'],
        ratio: '8:2',
        watched: '35 million',
        rewatched: '10 million',
        image: movie10,
    },
    {
        id: 11,
        title: 'Family Guy',
        description: 'In a wacky Rhode Island town, a dysfunctional family strive to cope with everyday life as they are thrown from one crazy scenario to another.',
        duration: '19 Seasons',
        rating: 'TV-14',
        reviews: '8.1/10',
        cast: ['Seth MacFarlane', 'Alex Borstein', 'Seth Green'],
        genre: ['Animation', 'Comedy'],
        ratio: '7:3',
        watched: '20 million',
        rewatched: '1.3 million',
        image: movie11,
    },
    {
        id: 12,
        title: 'Rick and Morty',
        description: 'An animated series that follows the exploits of a super scientist and his not-so-bright grandson.',
        duration: '5 Seasons',
        rating: 'TV-MA',
        reviews: '9.2/10',
        cast: ['Justin Roiland', 'Chris Parnell', 'Spencer Grammer'],
        genre: ['Animation', 'Adventure', 'Comedy'],
        ratio: '9:2',
        watched: '40 million',
        rewatched: '8 million',
        image: movie12,
    },
    {
        id: 13,
        title: 'The Godfather Part II',
        description: 'The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.',
        duration: '202 min',
        rating: 'R',
        reviews: '9.0/10',
        cast: ['Al Pacino', 'Robert De Niro', 'Robert Duvall'],
        genre: ['Crime', 'Drama'],
        ratio: '9:2',
        watched: '40 million',
        rewatched: '2.1 million',
        image: movie13,
    },
    {
        id: 14,
        title: 'The Godfather Part III',
        description: 'Follows Michael Corleone, now in his 60s, as he seeks to free his family from crime and find a suitable successor to his empire.',
        duration: '162 min',
        rating: 'R',
        reviews: '7.6/10',
        cast: ['Al Pacino', 'Diane Keaton', 'Andy Garcia'],
        genre: ['Crime', 'Drama'],
        ratio: '9:2',
        watched: '35 million',
        rewatched: '2.2 million',
        image: movie14,
    },
    {
        id: 15,
        title: 'Avengers: Infinity War',
        description: 'The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.',
        duration: '149 min',
        rating: 'PG-13',
        reviews: '8.4/10',
        cast: ['Robert Downey Jr.', 'Chris Hemsworth', 'Mark Ruffalo'],
        genre: ['Action', 'Adventure', 'Sci-Fi'],
        ratio: '11:0',
        watched: '500 million',
        rewatched: '200 million',
        image: movie15,
    },
    {
        id: 16,
        title: 'Joker',
        description: 'In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime.',
        duration: '122 min',
        rating: 'R',
        reviews: '8.4/10',
        cast: ['Joaquin Phoenix', 'Robert De Niro', 'Zazie Beetz'],
        genre: ['Crime', 'Drama', 'Thriller'],
        ratio: '9:2',
        watched: '30 million',
        rewatched: '2.5 million',
        image: movie16,
    },
    {
        id: 17,
        title: 'Ted',
        description: 'John Bennett, a man whose childhood wish of bringing his teddy bear to life came true, now must decide between keeping the relationship with the bear, Ted or his girlfriend, Lori.',
        duration: '106 min',
        rating: 'R',
        reviews: '6.9/10',
        cast: ['Mark Wahlberg', 'Mila Kunis', 'Seth MacFarlane'],
        genre: ['Comedy', 'Fantasy'],
        ratio: '7:3',
        watched: '18 million',
        rewatched: '1.5 million',
        image: movie17,
    },
    {
        id: 18,
        title: 'Brooklyn Nine-Nine',
        description: 'Comedy series about detectives in the fictional 99th Precinct of the NYPD in Brooklyn, New York City.',
        duration: '8 Seasons',
        rating: 'TV-14',
        reviews: '8.4/10',
        cast: ['Andy Samberg', 'Terry Crews', 'Stephanie Beatriz'],
        genre: ['Comedy', 'Crime'],
        ratio: '9:2',
        watched: '40 million',
        rewatched: '8 million',
        image: movie18,
    },
    {
        id: 19,
        title: 'The Office',
        description: 'A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium.',
        duration: '9 Seasons',
        rating: 'TV-14',
        reviews: '8.9/10',
        cast: ['Steve Carell', 'Jenna Fischer', 'John Krasinski'],
        genre: ['Comedy'],
        ratio: '10:1',
        watched: '30 million',
        rewatched: '5 million',
        image: movie19,
    },
    {
        id: 20,
        title: 'Vinland Saga',
        description: 'Thorfinn pursues a journey with his father\'s killer in order to take revenge and end his life in a duel as an honorable warrior and pay his father a homage.',
        duration: '1 Season',
        rating: 'TV-MA',
        reviews: '8.8/10',
        cast: ['Shizuka Ishigami', 'Yûto Uemura', 'Kenichiro Matsuda'],
        genre: ['Animation', 'Action', 'Adventure'],
        ratio: '8:2',
        watched: '4 million',
        rewatched: '1 million',
        image: movie20,
    },
    {
        id: 21,
        title: 'Spider-Man: Into the Spider-Verse',
        description: 'Teen Miles Morales becomes the Spider-Man of his universe, and must join with five spider-powered individuals from other dimensions to stop a threat for all realities.',
        duration: '117 min',
        rating: 'PG',
        reviews: '8.4/10',
        cast: ['Shameik Moore', 'Jake Johnson', 'Hailee Steinfeld'],
        genre: ['Animation', 'Action', 'Adventure'],
        ratio: '10:1',
        watched: '300 million',
        rewatched: '100 million',
        image: movie21,
    }
];

export default movieData;